name: parking_management_app
description: Parking lot management sample app in clean architecture with bloc state management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.3
  mocktail: ^1.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
